title: HCI Conference Deadlines
description: Countdowns to top HCI conference deadlines
author: Andrea Bianchi

domain: 'http://hci-deadlines.kaist.id'
baseurl: ''

twitter_hashtag: hci
github_username: makinteractlab
github_repo: hci-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
