title: ⏰ SUPERgroup Conference Deadlines
description: Countdowns to HCI, Security/Privacy, and Fairness conference deadlines
author: SUPER

domain: 'https://uchicagosupergroup.github.io/supergroup-deadlines'
baseurl: ''

# twitter_hashtag: hci-deadlines
github_username: cmdkev
github_repo: supergroup-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
